# Generated by Django 6.0.5 on 2026-06-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SzablonWiadomosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa szablonu')),
                ('tresc', models.TextField(verbose_name='Treść szablonu (HTML)')),
            ],
            options={
                'verbose_name': 'Szablon wiadomości',
                'verbose_name_plural': 'Szablony wiadomości',
            },
        ),
        migrations.CreateModel(
            name='ZgloszenieProblemu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor zgłoszenia (Imię/Email)')),
                ('temat', models.CharField(max_length=200, verbose_name='Temat zgłoszenia')),
                ('tresc', models.TextField(verbose_name='Treść – opis problemu')),
                ('modul', models.CharField(choices=[('oferta', 'Moduł Oferty Szkoleniowej'), ('rejestracja', 'Moduł Rejestracji i Zapisów'), ('panel', 'Panel Zarządzania (Manager)'), ('api', 'Interfejs API'), ('inne', 'Inne / Niezidentyfikowane')], default='inne', max_length=50, verbose_name='Wybór modułu aplikacji')),
                ('zalacznik', models.ImageField(blank=True, null=True, upload_to='problemy_zalaczniki/', verbose_name='Opcjonalny załącznik graficzny')),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True, verbose_name='Data i godzina zgłoszenia')),
            ],
            options={
                'verbose_name': 'Zgłoszenie problemu',
                'verbose_name_plural': 'Zgłoszenia problemów',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('kolejnosc', models.IntegerField(default=1, verbose_name='Kolejność')),
                ('publikuj', models.BooleanField(default=True, verbose_name='Publikuj')),
                ('kategoria_nadrzedna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podkategorie', to='offer.kategoria', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Szkolenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200, verbose_name='Tytuł szkolenia')),
                ('opis', models.TextField(verbose_name='Opis')),
                ('numer', models.CharField(max_length=50, verbose_name='Numer szkolenia')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('liczba_godzin', models.IntegerField(verbose_name='Liczba godzin')),
                ('kolejnosc', models.IntegerField(default=1, verbose_name='Kolejność')),
                ('publikuj', models.BooleanField(default=True, verbose_name='Publikuj')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szkolenia', to='offer.kategoria', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Szkolenie',
                'verbose_name_plural': 'Szkolenia',
            },
        ),
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres E-mail')),
                ('zgoda_rodo', models.BooleanField(default=False, verbose_name='Zgoda RODO')),
                ('szkolenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.szkolenie', verbose_name='Szkolenie')),
            ],
            options={
                'verbose_name': 'Rejestracja',
                'verbose_name_plural': 'Rejestracje',
            },
        ),
    ]
